#!/usr/bin/env node
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import { exec } from "node:child_process";
import { writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const server = new Server(
  { name: "workflow-html-app", version: "1.0.0" },
  { capabilities: { tools: {} } }
);

function openBrowser(filePath) {
  const cmd =
    process.platform === "darwin"
      ? "open"
      : process.platform === "win32"
        ? 'start ""'
        : "xdg-open";
  exec(`${cmd} "${filePath}"`);
}

function escapeHtml(str) {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function generatePlanViewerHtml(content) {
  const now = new Date().toLocaleString("ja-JP");
  return `<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Plan Viewer — Claude Workflow</title>
<script src="https://cdn.jsdelivr.net/npm/marked@9/marked.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/dompurify@3/dist/purify.min.js"></script>
<style>
:root{--bg:#f8fafc;--fg:#0f172a;--accent:#4f46e5;--card:#fff;--border:#e2e8f0;--code:#f1f5f9;--muted:#64748b}
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:var(--bg);color:var(--fg);line-height:1.7;min-height:100vh;padding:2rem}
.header{background:linear-gradient(135deg,#4f46e5,#7c3aed);color:#fff;padding:1.25rem 2rem;border-radius:12px;margin-bottom:2rem;display:flex;align-items:center;gap:.75rem}
.header h1{font-size:1.1rem;font-weight:600;flex:1}
.badge{background:rgba(255,255,255,.2);padding:2px 10px;border-radius:999px;font-size:.72rem}
.content{background:var(--card);border-radius:12px;border:1px solid var(--border);padding:2.5rem;max-width:860px;margin:0 auto;box-shadow:0 1px 4px rgba(0,0,0,.06)}
.content h1{font-size:1.65rem;font-weight:700;margin:1.5rem 0 .6rem;border-bottom:2px solid var(--border);padding-bottom:.5rem}
.content h2{font-size:1.3rem;font-weight:600;margin:1.5rem 0 .5rem;color:var(--accent)}
.content h3{font-size:1.1rem;font-weight:600;margin:1.2rem 0 .4rem}
.content h4{font-size:.95rem;font-weight:600;margin:1rem 0 .35rem;color:var(--muted)}
.content p{margin:.7rem 0}
.content ul,.content ol{margin:.7rem 0;padding-left:1.6rem}
.content li{margin:.25rem 0}
.content code{background:var(--code);padding:2px 5px;border-radius:4px;font-size:.85em;font-family:"SF Mono",Monaco,Consolas,monospace}
.content pre{background:var(--code);padding:1.25rem;border-radius:8px;overflow-x:auto;margin:1rem 0;border:1px solid var(--border)}
.content pre code{background:none;padding:0}
.content blockquote{border-left:3px solid var(--accent);padding:.2rem 0 .2rem 1rem;color:var(--muted);margin:1rem 0}
.content table{width:100%;border-collapse:collapse;margin:1rem 0;font-size:.9rem}
.content th{background:var(--code);padding:.55rem 1rem;text-align:left;border:1px solid var(--border);font-weight:600}
.content td{padding:.55rem 1rem;border:1px solid var(--border)}
.content tr:nth-child(even) td{background:var(--bg)}
.content a{color:var(--accent);text-decoration:none}
.content a:hover{text-decoration:underline}
.content hr{border:none;border-top:1px solid var(--border);margin:2rem 0}
.content strong{font-weight:600}
.footer{text-align:center;color:var(--muted);font-size:.78rem;margin-top:1.5rem}
</style>
</head>
<body>
<div class="header">
  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"/></svg>
  <h1>Claude Workflow — Plan Viewer</h1>
  <span class="badge">Markdown</span>
</div>
<div class="content" id="content"></div>
<div class="footer">Generated by workflow-html-app &bull; ${now}</div>
<script>
const raw = ${JSON.stringify(content)};
marked.setOptions({breaks:true,gfm:true});
document.getElementById('content').innerHTML = DOMPurify.sanitize(marked.parse(raw));
const h1 = document.querySelector('h1');
if (h1) document.title = h1.textContent + ' — Plan Viewer';
</script>
</body>
</html>`;
}

function generateDiagramViewerHtml(mermaidCode, title = "Diagram") {
  const safeTitle = escapeHtml(title);
  return `<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${safeTitle} — Diagram Viewer</title>
<script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
<style>
:root{--bg:#0f172a;--card:#1e293b;--accent:#818cf8;--border:#334155;--fg:#e2e8f0;--muted:#94a3b8}
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:var(--bg);color:var(--fg);height:100vh;display:flex;flex-direction:column;overflow:hidden}
.toolbar{background:var(--card);border-bottom:1px solid var(--border);padding:.65rem 1.25rem;display:flex;align-items:center;gap:.75rem;flex-shrink:0}
.toolbar-title{font-size:.95rem;font-weight:600;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.btn{background:var(--border);color:var(--fg);border:none;padding:.35rem .85rem;border-radius:6px;cursor:pointer;font-size:.82rem;transition:background .12s}
.btn:hover{background:var(--accent);color:#fff}
.zoom-info{color:var(--muted);font-size:.8rem;min-width:52px;text-align:center;font-variant-numeric:tabular-nums}
.canvas{flex:1;overflow:hidden;position:relative;cursor:grab;background:radial-gradient(circle at 50% 50%,#1e293b 0%,#0f172a 100%)}
.canvas:active{cursor:grabbing}
.diagram-wrapper{position:absolute;top:50%;left:50%;transform-origin:center center;user-select:none}
.mermaid svg{display:block;max-width:none!important}
.code-panel{background:var(--card);border-top:1px solid var(--border);padding:.6rem 1.25rem;font-size:.75rem;color:var(--muted);font-family:"SF Mono",Monaco,monospace;max-height:140px;overflow-y:auto;display:none;white-space:pre}
.code-panel.visible{display:block}
.loading{position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);color:var(--muted);font-size:.9rem}
</style>
</head>
<body>
<div class="toolbar">
  <span class="toolbar-title">${safeTitle}</span>
  <span class="zoom-info" id="zoomInfo">100%</span>
  <button class="btn" onclick="zoomIn()">＋</button>
  <button class="btn" onclick="zoomOut()">−</button>
  <button class="btn" onclick="resetView()">リセット</button>
  <button class="btn" onclick="fitToScreen()">フィット</button>
  <button class="btn" onclick="toggleCode()">コード</button>
</div>
<div class="canvas" id="canvas">
  <div class="loading" id="loading">レンダリング中...</div>
  <div class="diagram-wrapper" id="wrapper">
    <div class="mermaid" id="mermaidEl"></div>
  </div>
</div>
<div class="code-panel" id="codePanel"></div>
<script>
const mermaidCode = ${JSON.stringify(mermaidCode)};
mermaid.initialize({startOnLoad:false,theme:'dark',securityLevel:'loose'});

let scale=1,tx=0,ty=0,dragging=false,sx=0,sy=0;
const canvas=document.getElementById('canvas');
const wrapper=document.getElementById('wrapper');
const zoomInfo=document.getElementById('zoomInfo');

function updateT(){
  wrapper.style.transform='translate(calc(-50% + '+tx+'px), calc(-50% + '+ty+'px)) scale('+scale+')';
  zoomInfo.textContent=Math.round(scale*100)+'%';
}
function zoomIn(){scale=Math.min(scale*1.2,8);updateT();}
function zoomOut(){scale=Math.max(scale/1.2,.05);updateT();}
function resetView(){scale=1;tx=0;ty=0;updateT();}
function fitToScreen(){
  const svg=wrapper.querySelector('svg');
  if(!svg)return;
  const rect=svg.getBoundingClientRect();
  const sw=rect.width/scale;
  const sh=rect.height/scale;
  const cw=canvas.clientWidth;
  const ch=canvas.clientHeight;
  scale=Math.min((cw-80)/sw,(ch-80)/sh,2);
  tx=0;ty=0;updateT();
}
function toggleCode(){document.getElementById('codePanel').classList.toggle('visible');}

canvas.addEventListener('wheel',e=>{
  e.preventDefault();
  scale=Math.max(.05,Math.min(8,scale*(e.deltaY>0?.9:1.1)));
  updateT();
},{passive:false});
canvas.addEventListener('mousedown',e=>{dragging=true;sx=e.clientX-tx;sy=e.clientY-ty;});
document.addEventListener('mousemove',e=>{if(!dragging)return;tx=e.clientX-sx;ty=e.clientY-sy;updateT();});
document.addEventListener('mouseup',()=>{dragging=false;});

document.getElementById('codePanel').textContent=mermaidCode;

(async()=>{
  try{
    const{svg}=await mermaid.render('diagram-'+Date.now(),mermaidCode);
    document.getElementById('mermaidEl').innerHTML=svg;
    document.getElementById('loading').remove();
    updateT();
  }catch(err){
    document.getElementById('loading').innerHTML='<span style="color:#f87171">レンダリングエラー: '+escHtml(err.message)+'</span>';
  }
})();

function escHtml(s){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
</script>
</body>
</html>`;
}

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: "view-plan",
      description:
        "Markdownコンテンツを計画/ログHTMLビューアで表示する。Phase 2の30_plan.mdやPhase 5の05_log.mdの表示に使用。",
      inputSchema: {
        type: "object",
        properties: {
          content: {
            type: "string",
            description: "表示するMarkdownコンテンツ",
          },
        },
        required: ["content"],
      },
    },
    {
      name: "view-diagram",
      description:
        "MermaidコードをインタラクティブHTMLビューアで表示する。ズーム・パン操作が可能。",
      inputSchema: {
        type: "object",
        properties: {
          mermaidCode: {
            type: "string",
            description: "表示するMermaidコード",
          },
          title: {
            type: "string",
            description: "図のタイトル（省略可）",
          },
        },
        required: ["mermaidCode"],
      },
    },
  ],
}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  if (name === "view-plan") {
    const content = args?.content;
    if (!content) throw new Error("content is required");
    const html = generatePlanViewerHtml(String(content));
    const file = join(tmpdir(), `plan-viewer-${Date.now()}.html`);
    writeFileSync(file, html, "utf-8");
    openBrowser(file);
    return {
      content: [{ type: "text", text: `Plan Viewerを開きました: ${file}` }],
    };
  }

  if (name === "view-diagram") {
    const mermaidCode = args?.mermaidCode;
    const title = args?.title ?? "Diagram";
    if (!mermaidCode) throw new Error("mermaidCode is required");
    const html = generateDiagramViewerHtml(String(mermaidCode), String(title));
    const file = join(tmpdir(), `diagram-viewer-${Date.now()}.html`);
    writeFileSync(file, html, "utf-8");
    openBrowser(file);
    return {
      content: [
        {
          type: "text",
          text: `Diagram Viewerを開きました\nタイトル: ${title}\nファイル: ${file}`,
        },
      ],
    };
  }

  throw new Error(`Unknown tool: ${name}`);
});

const transport = new StdioServerTransport();
await server.connect(transport);
